/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Vista.secciones;

import BD.CProducto;
import static Vista.secciones.Principal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofia Useche
 */
public class Gastos extends javax.swing.JPanel {

    /**
     * Creates new form Gastos
     */
    private CProducto objetoProducto;
    public Gastos() {
        initComponents();
        desabilitarformulario();
        BD.CGasto objetoProveedor = new BD.CGasto();
        objetoProveedor.mostrarProveedores(cbProveedor);
        objetoProveedor.mostrarProveedores(cbProveedor1);
        objetoProveedor.mostrarProveedores(cbProveedor2);
        /*objetoProducto.mostrarMarca(cbMarca);
        objetoProducto.mostrarPresentacion(cbPresentacion);
        objetoProducto.mostrarUnidadMedida(cbUnidadMedida);*/
        BD.CGasto objetoGasto = new BD.CGasto();
        objetoGasto.mostrarGasto(jtGasto);
        txtCodigo.setEnabled(false);
        jtGasto.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        jtGasto.getTableHeader().setOpaque(false);
        jtGasto.getTableHeader().setBackground(new Color(58,179,28));
        jtGasto.getTableHeader().setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelCubierta = new javax.swing.JTabbedPane();
        CubiertaNuevo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnGuardarGasto = new javax.swing.JButton();
        BotonSallir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnNuevoProveedor = new javax.swing.JButton();
        txtProducto = new RSMaterialComponent.RSTextFieldMaterial();
        txtPrecio = new RSMaterialComponent.RSTextFieldMaterial();
        txtDescripcion = new RSMaterialComponent.RSTextFieldMaterial();
        txtCantidad = new RSMaterialComponent.RSTextFieldMaterial();
        cbProveedor = new RSMaterialComponent.RSComboBoxMaterial();
        dtFecha = new com.toedter.calendar.JDateChooser();
        BtnNuevaBebida = new javax.swing.JButton();
        CubiertaProveedor = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnGuardarProveedor = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        txtNombreProveedor = new RSMaterialComponent.RSTextFieldMaterial();
        txtTelefono = new RSMaterialComponent.RSTextFieldMaterial();
        txtCorreo = new RSMaterialComponent.RSTextFieldMaterial();
        txtDireccion = new RSMaterialComponent.RSTextFieldMaterial();
        txtTipoProducto = new RSMaterialComponent.RSTextFieldMaterial();
        CubiertaModificar = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnGuardarModificacion = new javax.swing.JButton();
        btnSalir3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtCodigo = new RSMaterialComponent.RSTextFieldMaterial();
        txtProducto1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtPrecio1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtDescripcion1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtCantidad1 = new RSMaterialComponent.RSTextFieldMaterial();
        cbProveedor1 = new RSMaterialComponent.RSComboBoxMaterial();
        dtFecha1 = new com.toedter.calendar.JDateChooser();
        CubiertaBebida = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnGuardarBebida = new javax.swing.JButton();
        BotonSalir4 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txtProducto2 = new RSMaterialComponent.RSTextFieldMaterial();
        txtPrecio2 = new RSMaterialComponent.RSTextFieldMaterial();
        txtDescripcion2 = new RSMaterialComponent.RSTextFieldMaterial();
        txtCantidad2 = new RSMaterialComponent.RSTextFieldMaterial();
        cbProveedor2 = new RSMaterialComponent.RSComboBoxMaterial();
        dtFecha2 = new com.toedter.calendar.JDateChooser();
        cbUnidadMedida = new RSMaterialComponent.RSComboBoxMaterial();
        cbMarca = new RSMaterialComponent.RSComboBoxMaterial();
        cbPresentacion = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnNuevoProveedor2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtGasto = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        barrabuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotonNuevo = new RSMaterialComponent.RSButtonShapeIcon();
        BtnStockBebidas = new RSMaterialComponent.RSButtonShapeIcon();
        BotonProveedor = new RSMaterialComponent.RSButtonShapeIcon();
        btnModificar = new RSMaterialComponent.RSButtonShapeIcon();
        btnEliminar = new RSMaterialComponent.RSButtonShapeIcon();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCubierta.setBackground(new java.awt.Color(255, 255, 255));
        PanelCubierta.setPreferredSize(new java.awt.Dimension(800, 700));
        PanelCubierta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCubiertaMouseClicked(evt);
            }
        });

        CubiertaNuevo.setPreferredSize(new java.awt.Dimension(800, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nuevo Gasto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Cantidad");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Fecha");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Precio");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Proveedor");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Producto");

        btnGuardarGasto.setBackground(new java.awt.Color(58, 179, 28));
        btnGuardarGasto.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarGasto.setText("Guardar");
        btnGuardarGasto.setBorder(null);
        btnGuardarGasto.setBorderPainted(false);
        btnGuardarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarGastoActionPerformed(evt);
            }
        });

        BotonSallir.setBackground(new java.awt.Color(153, 153, 153));
        BotonSallir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSallir.setText("Cancelar");
        BotonSallir.setBorder(null);
        BotonSallir.setBorderPainted(false);
        BotonSallir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSallirActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Descripcion");

        btnNuevoProveedor.setBackground(new java.awt.Color(58, 179, 28));
        btnNuevoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-18.png"))); // NOI18N
        btnNuevoProveedor.setBorder(null);
        btnNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProveedorActionPerformed(evt);
            }
        });

        txtProducto.setForeground(new java.awt.Color(51, 51, 51));
        txtProducto.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtProducto.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtProducto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtProducto.setPhColor(new java.awt.Color(51, 51, 51));
        txtProducto.setPlaceholder("Ingrese el producto");

        txtPrecio.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecio.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPrecio.setPhColor(new java.awt.Color(51, 51, 51));
        txtPrecio.setPlaceholder("Ingrese el precio");

        txtDescripcion.setForeground(new java.awt.Color(51, 51, 51));
        txtDescripcion.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescripcion.setPhColor(new java.awt.Color(51, 51, 51));
        txtDescripcion.setPlaceholder("Ingrese la descripcion");

        txtCantidad.setForeground(new java.awt.Color(51, 51, 51));
        txtCantidad.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCantidad.setPhColor(new java.awt.Color(51, 51, 51));
        txtCantidad.setPlaceholder("Ingrese la cantidad");

        cbProveedor.setColorMaterial(new java.awt.Color(58, 179, 28));
        cbProveedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        BtnNuevaBebida.setBackground(new java.awt.Color(58, 179, 28));
        BtnNuevaBebida.setForeground(new java.awt.Color(255, 255, 255));
        BtnNuevaBebida.setText("Nueva Bebidas");
        BtnNuevaBebida.setBorder(null);
        BtnNuevaBebida.setBorderPainted(false);
        BtnNuevaBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevaBebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(153, 153, 153))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNuevoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(BtnNuevaBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonSallir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnGuardarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(dtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel10))
                    .addComponent(btnNuevoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSallir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNuevaBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CubiertaNuevoLayout = new javax.swing.GroupLayout(CubiertaNuevo);
        CubiertaNuevo.setLayout(CubiertaNuevoLayout);
        CubiertaNuevoLayout.setHorizontalGroup(
            CubiertaNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CubiertaNuevoLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        CubiertaNuevoLayout.setVerticalGroup(
            CubiertaNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CubiertaNuevoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
        );

        PanelCubierta.addTab("tab1", CubiertaNuevo);

        CubiertaProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Nuevo Proveedor");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Telefono");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Nombre");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Direccion");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Tipo de producto");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Correo");

        btnGuardarProveedor.setBackground(new java.awt.Color(58, 179, 28));
        btnGuardarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarProveedor.setText("Guardar");
        btnGuardarProveedor.setBorder(null);
        btnGuardarProveedor.setBorderPainted(false);
        btnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedorActionPerformed(evt);
            }
        });

        btnSalir2.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir2.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir2.setText("Cancelar");
        btnSalir2.setBorder(null);
        btnSalir2.setBorderPainted(false);
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        txtNombreProveedor.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreProveedor.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtNombreProveedor.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtNombreProveedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNombreProveedor.setPhColor(new java.awt.Color(51, 51, 51));
        txtNombreProveedor.setPlaceholder("Ingrese el nombre");

        txtTelefono.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefono.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtTelefono.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTelefono.setPhColor(new java.awt.Color(51, 51, 51));
        txtTelefono.setPlaceholder("Ingrese el telefono");

        txtCorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtCorreo.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtCorreo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCorreo.setPhColor(new java.awt.Color(51, 51, 51));
        txtCorreo.setPlaceholder("Ingrese el correo");

        txtDireccion.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccion.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtDireccion.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDireccion.setPhColor(new java.awt.Color(51, 51, 51));
        txtDireccion.setPlaceholder("Ingrese la direccion");

        txtTipoProducto.setForeground(new java.awt.Color(51, 51, 51));
        txtTipoProducto.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtTipoProducto.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtTipoProducto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTipoProducto.setPhColor(new java.awt.Color(51, 51, 51));
        txtTipoProducto.setPlaceholder("Ingrese el tipo de producto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnGuardarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16)
                                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        CubiertaProveedor.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 450, 340));

        PanelCubierta.addTab("tab2", CubiertaProveedor);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Modificar Gasto");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Cantidad");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Codigo");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Fecha");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Precio");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Proveedor");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Producto");

        btnGuardarModificacion.setBackground(new java.awt.Color(58, 179, 28));
        btnGuardarModificacion.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarModificacion.setText("Guardar");
        btnGuardarModificacion.setBorder(null);
        btnGuardarModificacion.setBorderPainted(false);
        btnGuardarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModificacionActionPerformed(evt);
            }
        });

        btnSalir3.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir3.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir3.setText("Cancelar");
        btnSalir3.setBorder(null);
        btnSalir3.setBorderPainted(false);
        btnSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir3ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Descripcion");

        txtCodigo.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigo.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCodigo.setPhColor(new java.awt.Color(51, 51, 51));
        txtCodigo.setPlaceholder("");

        txtProducto1.setForeground(new java.awt.Color(51, 51, 51));
        txtProducto1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtProducto1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtProducto1.setPhColor(new java.awt.Color(51, 51, 51));
        txtProducto1.setPlaceholder("Ingrese el producto");

        txtPrecio1.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecio1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtPrecio1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPrecio1.setPhColor(new java.awt.Color(51, 51, 51));
        txtPrecio1.setPlaceholder("Ingrese el producto");

        txtDescripcion1.setForeground(new java.awt.Color(51, 51, 51));
        txtDescripcion1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtDescripcion1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescripcion1.setPhColor(new java.awt.Color(51, 51, 51));
        txtDescripcion1.setPlaceholder("Ingrese el producto");

        txtCantidad1.setForeground(new java.awt.Color(51, 51, 51));
        txtCantidad1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtCantidad1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCantidad1.setPhColor(new java.awt.Color(51, 51, 51));
        txtCantidad1.setPlaceholder("Ingrese el producto");

        cbProveedor1.setColorMaterial(new java.awt.Color(58, 179, 28));
        cbProveedor1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(btnSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(btnGuardarModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(txtDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(dtFecha1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel15))
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProveedor1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout CubiertaModificarLayout = new javax.swing.GroupLayout(CubiertaModificar);
        CubiertaModificar.setLayout(CubiertaModificarLayout);
        CubiertaModificarLayout.setHorizontalGroup(
            CubiertaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CubiertaModificarLayout.createSequentialGroup()
                .addGap(0, 247, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 247, Short.MAX_VALUE))
        );
        CubiertaModificarLayout.setVerticalGroup(
            CubiertaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CubiertaModificarLayout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );

        PanelCubierta.addTab("tab3", CubiertaModificar);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nueva Bebida");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Cantidad");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Fecha");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Precio");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Proveedor");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Producto");

        btnGuardarBebida.setBackground(new java.awt.Color(58, 179, 28));
        btnGuardarBebida.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarBebida.setText("Guardar");
        btnGuardarBebida.setBorder(null);
        btnGuardarBebida.setBorderPainted(false);
        btnGuardarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarBebidaActionPerformed(evt);
            }
        });

        BotonSalir4.setBackground(new java.awt.Color(255, 51, 51));
        BotonSalir4.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir4.setText("Cancelar");
        BotonSalir4.setBorder(null);
        BotonSalir4.setBorderPainted(false);
        BotonSalir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalir4ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Descripcion");

        txtProducto2.setForeground(new java.awt.Color(51, 51, 51));
        txtProducto2.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtProducto2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtProducto2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtProducto2.setPhColor(new java.awt.Color(51, 51, 51));
        txtProducto2.setPlaceholder("Ingrese el producto");

        txtPrecio2.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecio2.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtPrecio2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPrecio2.setPhColor(new java.awt.Color(51, 51, 51));
        txtPrecio2.setPlaceholder("Ingrese el precio");

        txtDescripcion2.setForeground(new java.awt.Color(51, 51, 51));
        txtDescripcion2.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtDescripcion2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescripcion2.setPhColor(new java.awt.Color(51, 51, 51));
        txtDescripcion2.setPlaceholder("Ingrese la descripcion");

        txtCantidad2.setForeground(new java.awt.Color(51, 51, 51));
        txtCantidad2.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtCantidad2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCantidad2.setPhColor(new java.awt.Color(51, 51, 51));
        txtCantidad2.setPlaceholder("Ingrese la cantidad");

        cbProveedor2.setColorMaterial(new java.awt.Color(58, 179, 28));
        cbProveedor2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        cbUnidadMedida.setColorMaterial(new java.awt.Color(58, 179, 28));
        cbUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        cbMarca.setColorMaterial(new java.awt.Color(58, 179, 28));
        cbMarca.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        cbPresentacion.setColorMaterial(new java.awt.Color(58, 179, 28));
        cbPresentacion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Unidad de medida");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Presentación");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Marca");

        btnNuevoProveedor2.setBackground(new java.awt.Color(58, 179, 28));
        btnNuevoProveedor2.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProveedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-18.png"))); // NOI18N
        btnNuevoProveedor2.setBorder(null);
        btnNuevoProveedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProveedor2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel30))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(153, 153, 153))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtProducto2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPrecio2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDescripcion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel25)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel27)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnNuevoProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cbProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(dtFecha2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                            .addComponent(txtCantidad2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addComponent(cbPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel31)))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(BotonSalir4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnGuardarBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel28))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(dtFecha2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cbProveedor2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonSalir4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnNuevoProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout CubiertaBebidaLayout = new javax.swing.GroupLayout(CubiertaBebida);
        CubiertaBebida.setLayout(CubiertaBebidaLayout);
        CubiertaBebidaLayout.setHorizontalGroup(
            CubiertaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CubiertaBebidaLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        CubiertaBebidaLayout.setVerticalGroup(
            CubiertaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CubiertaBebidaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCubierta.addTab("tab4", CubiertaBebida);

        jPanel1.add(PanelCubierta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 630));

        jtGasto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jtGasto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtGasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtGasto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtGasto.setGridColor(new java.awt.Color(204, 204, 204));
        jtGasto.setRowHeight(30);
        jtGasto.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jtGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtGastoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtGasto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 890, 490));

        buscar.setBackground(new java.awt.Color(58, 179, 28));
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar.png"))); // NOI18N
        buscar.setBorder(null);
        buscar.setBorderPainted(false);
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 50, 30));

        barrabuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(barrabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Gastos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        BotonNuevo.setBackground(new java.awt.Color(58, 179, 28));
        BotonNuevo.setText("Nuevo");
        BotonNuevo.setBackgroundHover(new java.awt.Color(0, 153, 0));
        BotonNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonNuevo.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        BotonNuevo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        BotonNuevo.setSizeIcon(20.0F);
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 112, 35));

        BtnStockBebidas.setBackground(new java.awt.Color(58, 179, 28));
        BtnStockBebidas.setText("Stock");
        BtnStockBebidas.setBackgroundHover(new java.awt.Color(0, 153, 0));
        BtnStockBebidas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnStockBebidas.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        BtnStockBebidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCAL_DRINK);
        BtnStockBebidas.setSizeIcon(20.0F);
        BtnStockBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStockBebidasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnStockBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 112, 35));

        BotonProveedor.setBackground(new java.awt.Color(58, 179, 28));
        BotonProveedor.setText("Proveedores");
        BotonProveedor.setBackgroundHover(new java.awt.Color(0, 153, 0));
        BotonProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonProveedor.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        BotonProveedor.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SUPERVISOR_ACCOUNT);
        BotonProveedor.setSizeIcon(20.0F);
        BotonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(BotonProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 140, 35));

        btnModificar.setBackground(new java.awt.Color(58, 179, 28));
        btnModificar.setText("Modificar");
        btnModificar.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnModificar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnModificar.setSizeIcon(20.0F);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 120, 35));

        btnEliminar.setBackground(new java.awt.Color(58, 179, 28));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnEliminar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEliminar.setSizeIcon(20.0F);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 112, 35));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedorActionPerformed
        BD.CProveedor objetoProveedores = new BD.CProveedor();
        objetoProveedores.agregarProveedor(txtNombreProveedor, txtTelefono, txtCorreo, txtDireccion, txtTipoProducto);
    }//GEN-LAST:event_btnGuardarProveedorActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        PanelCubierta.setVisible(false);
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void PanelCubiertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCubiertaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCubiertaMouseClicked

    private void jtGastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtGastoMouseClicked

    }//GEN-LAST:event_jtGastoMouseClicked

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String textoBusqueda = barrabuscar.getText().trim(); // Obtener texto del JTextField

        // Verificar que no esté vacío
        if (textoBusqueda.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Ingrese un producto o proveedor válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Si es un número, podría ser un código de proveedor (opcional), pero permitimos texto también
        if (!textoBusqueda.matches("[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ ]+")) { 
            JOptionPane.showMessageDialog(this, "Ingrese solo letras o números.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        BD.CGasto obgasto = new BD.CGasto();
        obgasto.buscarGasto(jtGasto, textoBusqueda); // Llamar la función de búsqueda

    }//GEN-LAST:event_buscarActionPerformed

    private void btnGuardarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarGastoActionPerformed
        BD.CGasto objetoGasto = new BD.CGasto();
        objetoGasto.agregarGasto(txtProducto, txtCantidad, dtFecha, txtPrecio, txtDescripcion, cbProveedor);
        objetoGasto.mostrarGasto(jtGasto);
        desabilitarformulario();
    }//GEN-LAST:event_btnGuardarGastoActionPerformed

    private void BotonSallirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSallirActionPerformed
        desabilitarformulario();
    }//GEN-LAST:event_BotonSallirActionPerformed

    private void btnNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProveedorActionPerformed
        CubiertaNuevo.setVisible(false);
        CubiertaProveedor.setBackground(new Color(230, 230, 230, 240));
        PanelCubierta.setVisible(true);
        PanelCubierta.removeAll();
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
        PanelCubierta.add(CubiertaProveedor);
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
    }//GEN-LAST:event_btnNuevoProveedorActionPerformed

    private void btnSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir3ActionPerformed
        PanelCubierta.setVisible(false);
    }//GEN-LAST:event_btnSalir3ActionPerformed

    private void btnGuardarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModificacionActionPerformed
        BD.CGasto objetoGasto = new BD.CGasto();
        objetoGasto.modificarGasto(txtCodigo, txtProducto1, txtCantidad1, dtFecha1, txtPrecio1, txtDescripcion1, cbProveedor1);
        objetoGasto.mostrarGasto(jtGasto);
        desabilitarformulario();
        objetoGasto.limpiarFormulario(txtProducto1, txtCantidad1, dtFecha1, txtPrecio1, txtDescripcion1, cbProveedor1);
    }//GEN-LAST:event_btnGuardarModificacionActionPerformed

    private void btnGuardarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarBebidaActionPerformed
        objetoProducto.agregarBebidas(txtProducto2, txtCantidad2, dtFecha2, txtPrecio2, txtDescripcion2, cbProveedor2, cbMarca, cbPresentacion, cbUnidadMedida);
        desabilitarformulario();
    }//GEN-LAST:event_btnGuardarBebidaActionPerformed

    private void BotonSalir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalir4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalir4ActionPerformed

    private void btnNuevoProveedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProveedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoProveedor2ActionPerformed

    private void BtnNuevaBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevaBebidaActionPerformed
        CubiertaNuevo.setVisible(false);
        CubiertaProveedor.setBackground(new Color(230, 230, 230, 240));
        PanelCubierta.setVisible(true);
        PanelCubierta.removeAll();
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
        PanelCubierta.add(CubiertaBebida);
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
    }//GEN-LAST:event_BtnNuevaBebidaActionPerformed

    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        CubiertaNuevo.setBackground(new Color(230, 230, 230, 240));
        PanelCubierta.setVisible(true);
        PanelCubierta.removeAll();
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
        PanelCubierta.add(CubiertaNuevo);
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
    }//GEN-LAST:event_BotonNuevoActionPerformed

    private void BtnStockBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStockBebidasActionPerformed
        Producto in = new Producto();
        in.setSize(789, 700);
        in.setLocation(0,0);
        
        Principal.removeAll();
        Principal.add(in, BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();
    }//GEN-LAST:event_BtnStockBebidasActionPerformed

    private void BotonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProveedorActionPerformed
        Proveedores in = new Proveedores();
        in.setSize(789, 700);
        in.setLocation(0,0);
        
        Principal.removeAll();
        Principal.add(in, BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();
    }//GEN-LAST:event_BotonProveedorActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int selectedCount = 0;
        for (int i = 0; i < jtGasto.getRowCount(); i++) {
            Boolean seleccionado = (Boolean) jtGasto.getValueAt(i, 0);
            if (seleccionado != null && seleccionado) {
                selectedCount++;
            }
        }
        if (selectedCount == 1) {
            BD.CGasto objetoGasto = new BD.CGasto();
            CubiertaModificar.setBackground(new Color(230, 230, 230, 240));
            PanelCubierta.setVisible(true);
            PanelCubierta.removeAll();
            PanelCubierta.repaint();
            PanelCubierta.revalidate();
            PanelCubierta.add(CubiertaModificar);
            PanelCubierta.repaint();
            PanelCubierta.revalidate();
            objetoGasto.Seleccionar(jtGasto, txtCodigo, txtProducto1, txtCantidad1, dtFecha1, txtPrecio1, txtDescripcion1, cbProveedor1);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un solo registro para modificar.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        BD.CGasto objetoGasto = new BD.CGasto();
        objetoGasto.eliminarGasto(jtGasto);
        objetoGasto.mostrarGasto(jtGasto);
    }//GEN-LAST:event_btnEliminarActionPerformed
 
    public void desabilitarformulario(){
        PanelCubierta.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShapeIcon BotonNuevo;
    private RSMaterialComponent.RSButtonShapeIcon BotonProveedor;
    private javax.swing.JButton BotonSalir4;
    private javax.swing.JButton BotonSallir;
    private javax.swing.JButton BtnNuevaBebida;
    private RSMaterialComponent.RSButtonShapeIcon BtnStockBebidas;
    private javax.swing.JPanel CubiertaBebida;
    private javax.swing.JPanel CubiertaModificar;
    private javax.swing.JPanel CubiertaNuevo;
    private javax.swing.JPanel CubiertaProveedor;
    private javax.swing.JTabbedPane PanelCubierta;
    private javax.swing.JTextField barrabuscar;
    private RSMaterialComponent.RSButtonShapeIcon btnEliminar;
    private javax.swing.JButton btnGuardarBebida;
    private javax.swing.JButton btnGuardarGasto;
    private javax.swing.JButton btnGuardarModificacion;
    private javax.swing.JButton btnGuardarProveedor;
    private RSMaterialComponent.RSButtonShapeIcon btnModificar;
    private javax.swing.JButton btnNuevoProveedor;
    private javax.swing.JButton btnNuevoProveedor2;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JButton btnSalir3;
    private javax.swing.JButton buscar;
    private RSMaterialComponent.RSComboBoxMaterial cbMarca;
    private RSMaterialComponent.RSComboBoxMaterial cbPresentacion;
    private RSMaterialComponent.RSComboBoxMaterial cbProveedor;
    private RSMaterialComponent.RSComboBoxMaterial cbProveedor1;
    private RSMaterialComponent.RSComboBoxMaterial cbProveedor2;
    private RSMaterialComponent.RSComboBoxMaterial cbUnidadMedida;
    private com.toedter.calendar.JDateChooser dtFecha;
    private com.toedter.calendar.JDateChooser dtFecha1;
    private com.toedter.calendar.JDateChooser dtFecha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtGasto;
    private RSMaterialComponent.RSTextFieldMaterial txtCantidad;
    private RSMaterialComponent.RSTextFieldMaterial txtCantidad1;
    private RSMaterialComponent.RSTextFieldMaterial txtCantidad2;
    private RSMaterialComponent.RSTextFieldMaterial txtCodigo;
    private RSMaterialComponent.RSTextFieldMaterial txtCorreo;
    private RSMaterialComponent.RSTextFieldMaterial txtDescripcion;
    private RSMaterialComponent.RSTextFieldMaterial txtDescripcion1;
    private RSMaterialComponent.RSTextFieldMaterial txtDescripcion2;
    private RSMaterialComponent.RSTextFieldMaterial txtDireccion;
    private RSMaterialComponent.RSTextFieldMaterial txtNombreProveedor;
    private RSMaterialComponent.RSTextFieldMaterial txtPrecio;
    private RSMaterialComponent.RSTextFieldMaterial txtPrecio1;
    private RSMaterialComponent.RSTextFieldMaterial txtPrecio2;
    private RSMaterialComponent.RSTextFieldMaterial txtProducto;
    private RSMaterialComponent.RSTextFieldMaterial txtProducto1;
    private RSMaterialComponent.RSTextFieldMaterial txtProducto2;
    private RSMaterialComponent.RSTextFieldMaterial txtTelefono;
    private RSMaterialComponent.RSTextFieldMaterial txtTipoProducto;
    // End of variables declaration//GEN-END:variables
}
