/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Vista.secciones;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofia Useche
 */
public class Proveedores extends javax.swing.JPanel {

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        desabilitarformulario();
        BD.CProveedor objetoProveedor = new BD.CProveedor();
        objetoProveedor.mostrarProveedor(jtProveedor);
        jtProveedor.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        jtProveedor.getTableHeader().setOpaque(false);
        jtProveedor.getTableHeader().setBackground(new Color(58,179,28));
        jtProveedor.getTableHeader().setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelCubierta = new javax.swing.JTabbedPane();
        Cubierta1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnGuardarProveedor = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        txtNombreProveedor = new RSMaterialComponent.RSTextFieldMaterial();
        txtTelefono = new RSMaterialComponent.RSTextFieldMaterial();
        txtCorreo = new RSMaterialComponent.RSTextFieldMaterial();
        txtDireccion = new RSMaterialComponent.RSTextFieldMaterial();
        txtTipoProducto = new RSMaterialComponent.RSTextFieldMaterial();
        CubiertaModificar = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnGuardarProveedor1 = new javax.swing.JButton();
        btnSalir3 = new javax.swing.JButton();
        txtNombreProveedor1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtTelefono1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtCorreo1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtDireccion1 = new RSMaterialComponent.RSTextFieldMaterial();
        txtTipoProducto1 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel21 = new javax.swing.JLabel();
        txtCodigo = new RSMaterialComponent.RSTextFieldMaterial();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProveedor = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotonNuevo = new RSMaterialComponent.RSButtonShapeIcon();
        btnModificar = new RSMaterialComponent.RSButtonShapeIcon();
        btnEliminar = new RSMaterialComponent.RSButtonShapeIcon();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCubierta.setBackground(new java.awt.Color(255, 255, 255));
        PanelCubierta.setPreferredSize(new java.awt.Dimension(800, 700));
        PanelCubierta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCubiertaMouseClicked(evt);
            }
        });

        Cubierta1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Nuevo Proveedor");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Telefono");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Nombre");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Direccion");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Tipo de producto");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Correo");

        btnGuardarProveedor.setBackground(new java.awt.Color(58, 179, 28));
        btnGuardarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarProveedor.setText("Guardar");
        btnGuardarProveedor.setBorder(null);
        btnGuardarProveedor.setBorderPainted(false);
        btnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedorActionPerformed(evt);
            }
        });

        btnSalir2.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir2.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir2.setText("Cancelar");
        btnSalir2.setBorder(null);
        btnSalir2.setBorderPainted(false);
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        txtNombreProveedor.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreProveedor.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtNombreProveedor.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtNombreProveedor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNombreProveedor.setPhColor(new java.awt.Color(51, 51, 51));
        txtNombreProveedor.setPlaceholder("Ingrese el nombre");

        txtTelefono.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefono.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtTelefono.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTelefono.setPhColor(new java.awt.Color(51, 51, 51));
        txtTelefono.setPlaceholder("Ingrese el telefono");

        txtCorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtCorreo.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtCorreo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCorreo.setPhColor(new java.awt.Color(51, 51, 51));
        txtCorreo.setPlaceholder("Ingrese el correo");

        txtDireccion.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccion.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtDireccion.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDireccion.setPhColor(new java.awt.Color(51, 51, 51));
        txtDireccion.setPlaceholder("Ingrese la direccion");

        txtTipoProducto.setForeground(new java.awt.Color(51, 51, 51));
        txtTipoProducto.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtTipoProducto.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtTipoProducto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTipoProducto.setPhColor(new java.awt.Color(51, 51, 51));
        txtTipoProducto.setPlaceholder("Ingrese el tipo de producto");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnGuardarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16)
                                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        Cubierta1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 450, 340));

        PanelCubierta.addTab("tab2", Cubierta1);

        CubiertaModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Modificar Proveedor");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Telefono");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Nombre");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Direccion");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Tipo de producto");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Correo");

        btnGuardarProveedor1.setBackground(new java.awt.Color(58, 179, 28));
        btnGuardarProveedor1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarProveedor1.setText("Guardar");
        btnGuardarProveedor1.setBorder(null);
        btnGuardarProveedor1.setBorderPainted(false);
        btnGuardarProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedor1ActionPerformed(evt);
            }
        });

        btnSalir3.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir3.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir3.setText("Cancelar");
        btnSalir3.setBorder(null);
        btnSalir3.setBorderPainted(false);
        btnSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir3ActionPerformed(evt);
            }
        });

        txtNombreProveedor1.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreProveedor1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtNombreProveedor1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtNombreProveedor1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNombreProveedor1.setPhColor(new java.awt.Color(51, 51, 51));
        txtNombreProveedor1.setPlaceholder("Ingrese el nombre");

        txtTelefono1.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefono1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtTelefono1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtTelefono1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTelefono1.setPhColor(new java.awt.Color(51, 51, 51));
        txtTelefono1.setPlaceholder("Ingrese el telefono");

        txtCorreo1.setForeground(new java.awt.Color(51, 51, 51));
        txtCorreo1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtCorreo1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtCorreo1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCorreo1.setPhColor(new java.awt.Color(51, 51, 51));
        txtCorreo1.setPlaceholder("Ingrese el correo");

        txtDireccion1.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccion1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtDireccion1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtDireccion1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDireccion1.setPhColor(new java.awt.Color(51, 51, 51));
        txtDireccion1.setPlaceholder("Ingrese la direccion");

        txtTipoProducto1.setForeground(new java.awt.Color(51, 51, 51));
        txtTipoProducto1.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtTipoProducto1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtTipoProducto1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTipoProducto1.setPhColor(new java.awt.Color(51, 51, 51));
        txtTipoProducto1.setPlaceholder("Ingrese el tipo de producto");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Codigo");

        txtCodigo.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigo.setColorMaterial(new java.awt.Color(58, 179, 28));
        txtCodigo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCodigo.setPhColor(new java.awt.Color(51, 51, 51));
        txtCodigo.setPlaceholder("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addComponent(btnSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnGuardarProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                    .addGap(25, 25, 25))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(169, 169, 169))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(txtTipoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)
                                .addComponent(txtNombreProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))))
                    .addComponent(jLabel9))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        CubiertaModificar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 450, 340));

        PanelCubierta.addTab("tab2", CubiertaModificar);

        jPanel1.add(PanelCubierta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        jtProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jtProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jtProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtProveedor.setGridColor(new java.awt.Color(204, 204, 204));
        jtProveedor.setRowHeight(30);
        jtProveedor.setSelectionBackground(new java.awt.Color(187, 187, 187));
        jtProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProveedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtProveedor);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 740, 490));

        jButton3.setBackground(new java.awt.Color(58, 179, 28));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buscar.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 50, 30));

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Proveedores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        BotonNuevo.setBackground(new java.awt.Color(58, 179, 28));
        BotonNuevo.setText("Nuevo");
        BotonNuevo.setBackgroundHover(new java.awt.Color(0, 153, 0));
        BotonNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonNuevo.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        BotonNuevo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        BotonNuevo.setSizeIcon(20.0F);
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 112, 35));

        btnModificar.setBackground(new java.awt.Color(58, 179, 28));
        btnModificar.setText("Modificar");
        btnModificar.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnModificar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnModificar.setSizeIcon(20.0F);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, 35));

        btnEliminar.setBackground(new java.awt.Color(58, 179, 28));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnEliminar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEliminar.setSizeIcon(20.0F);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 112, 35));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PanelCubiertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCubiertaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCubiertaMouseClicked

    private void jtProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProveedorMouseClicked

    }//GEN-LAST:event_jtProveedorMouseClicked

    private void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedorActionPerformed
        BD.CProveedor objetoProveedores = new BD.CProveedor();
        objetoProveedores.agregarProveedor(txtNombreProveedor, txtTelefono, txtCorreo, txtDireccion, txtTipoProducto);
        objetoProveedores.mostrarProveedor(jtProveedor);
        desabilitarformulario();
    }//GEN-LAST:event_btnGuardarProveedorActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        PanelCubierta.setVisible(false);
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnGuardarProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedor1ActionPerformed
        BD.CProveedor objetoProveedor = new BD.CProveedor();
        objetoProveedor.modificarProveedor(txtCodigo, txtNombreProveedor1, txtTelefono1, txtCorreo1, txtDireccion1, txtTipoProducto1);
        objetoProveedor.mostrarProveedor(jtProveedor);
        desabilitarformulario();
    }//GEN-LAST:event_btnGuardarProveedor1ActionPerformed

    private void btnSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir3ActionPerformed

    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        Cubierta1.setBackground(new Color(230, 230, 230, 240));
        PanelCubierta.setVisible(true);
        PanelCubierta.removeAll();
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
        PanelCubierta.add(Cubierta1);
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
    }//GEN-LAST:event_BotonNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int selectedCount = 0;
        for (int i = 0; i < jtProveedor.getRowCount(); i++) {
            Boolean seleccionado = (Boolean) jtProveedor.getValueAt(i, 0);
            if (seleccionado != null && seleccionado) {
                selectedCount++;
            }
        }
        if (selectedCount == 1) {
            BD.CProveedor objetogProveedor = new BD.CProveedor();
            CubiertaModificar.setBackground(new Color(230, 230, 230, 240));
            PanelCubierta.setVisible(true);
            PanelCubierta.removeAll();
            PanelCubierta.repaint();
            PanelCubierta.revalidate();
            PanelCubierta.add(CubiertaModificar);
            PanelCubierta.repaint();
            PanelCubierta.revalidate();
            objetogProveedor.Seleccionar(jtProveedor, txtCodigo, txtNombreProveedor1, txtTelefono1, txtCorreo1, txtDireccion1, txtTipoProducto1);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un solo registro para modificar.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        BD.CProveedor objetoProveedor = new BD.CProveedor();
        objetoProveedor.eliminarProveedor(jtProveedor);
        objetoProveedor.mostrarProveedor(jtProveedor);
    }//GEN-LAST:event_btnEliminarActionPerformed
    public void desabilitarformulario(){
        PanelCubierta.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShapeIcon BotonNuevo;
    private javax.swing.JPanel Cubierta1;
    private javax.swing.JPanel CubiertaModificar;
    private javax.swing.JTabbedPane PanelCubierta;
    private RSMaterialComponent.RSButtonShapeIcon btnEliminar;
    private javax.swing.JButton btnGuardarProveedor;
    private javax.swing.JButton btnGuardarProveedor1;
    private RSMaterialComponent.RSButtonShapeIcon btnModificar;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JButton btnSalir3;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtProveedor;
    private RSMaterialComponent.RSTextFieldMaterial txtCodigo;
    private RSMaterialComponent.RSTextFieldMaterial txtCorreo;
    private RSMaterialComponent.RSTextFieldMaterial txtCorreo1;
    private RSMaterialComponent.RSTextFieldMaterial txtDireccion;
    private RSMaterialComponent.RSTextFieldMaterial txtDireccion1;
    private RSMaterialComponent.RSTextFieldMaterial txtNombreProveedor;
    private RSMaterialComponent.RSTextFieldMaterial txtNombreProveedor1;
    private RSMaterialComponent.RSTextFieldMaterial txtTelefono;
    private RSMaterialComponent.RSTextFieldMaterial txtTelefono1;
    private RSMaterialComponent.RSTextFieldMaterial txtTipoProducto;
    private RSMaterialComponent.RSTextFieldMaterial txtTipoProducto1;
    // End of variables declaration//GEN-END:variables
}
